#!/bin/bash

# sed (stream editor) is a Unix utility that parses and transforms text, 
# using a simple, compact programming language. 
# usage:
# 1. substitution command:
# sed 's/regexp/replacement/g' inputFileName > outputFileName
# 2. other sed commands
# sed '/^ *$/d' inputFileName # using d command to delete lines that are 
#                       # either blank or only contain space
# 3. used as a filter
# generate_data | sed 's/x/y/g' # "generate_data" generates data, and then 
#                       # sed makes the samll change of replacing x with y

while true; do
  sed -n -e '/^VmRSS/p' -e '/^VmSize/p' /proc/${1}/status
  sleep 1
done
